"""fix: add cnpj_dv to estabelecimento

Revision ID: 0086a13aea4e
Revises: 2f050edf2ba3
Create Date: 2024-04-24 18:49:19.072899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0086a13aea4e'
down_revision = '2f050edf2ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj_dv', sa.String(length=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.drop_column('cnpj_dv')

    # ### end Alembic commands ###
