"""cpf_cnpj nullable true

Revision ID: 01d81371195e
Revises: 359869a5200f
Create Date: 2024-04-03 20:47:36.257068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d81371195e'
down_revision = '359869a5200f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.alter_column('cpf_cnpj',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.alter_column('cpf_cnpj',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###
