"""add capital_social to empresa

Revision ID: 089c0b29c708
Revises: 2c2e97ebec2e
Create Date: 2024-03-25 21:41:34.390971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089c0b29c708'
down_revision = '2c2e97ebec2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capital_social', sa.Numeric(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('capital_social')

    # ### end Alembic commands ###
