"""cnpj unique

Revision ID: 124b186a1bf2
Revises: f03176d0be1d
Create Date: 2024-05-16 15:28:14.251635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124b186a1bf2'
down_revision = 'f03176d0be1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cnpj_basico'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
