"""initial db

Revision ID: 2c2e97ebec2e
Revises: 
Create Date: 2024-03-21 13:01:25.051132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2e97ebec2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnae',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('natureza_juridica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj_basico', sa.String(length=8), nullable=False),
    sa.Column('porte', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=100), nullable=False),
    sa.Column('natureza_juridica_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['natureza_juridica_id'], ['natureza_juridica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('socio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=15), nullable=False),
    sa.Column('nome_socio', sa.String(length=100), nullable=False),
    sa.Column('representante_legal', sa.String(length=8), nullable=True),
    sa.Column('nome_representante_legal', sa.String(length=100), nullable=True),
    sa.Column('qualificacao_id', sa.Integer(), nullable=False),
    sa.Column('representante_legal_qualificacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['qualificacao_id'], ['qualificacao.id'], ),
    sa.ForeignKeyConstraint(['representante_legal_qualificacao_id'], ['qualificacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa_cnae',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnae_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('primario', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cnae_id'], ['cnae.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('uf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uf_id'], ['uf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('socio_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(length=150), nullable=False),
    sa.Column('cep', sa.BigInteger(), nullable=False),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('tipo_logradouro', sa.String(length=50), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estabelecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj_basico', sa.String(length=8), nullable=False),
    sa.Column('cnpj_ordem', sa.String(length=4), nullable=False),
    sa.Column('identificador_matriz_filial', sa.Integer(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=100), nullable=False),
    sa.Column('data_inicio_atividade', sa.Date(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['endereco_id'], ['endereco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estabelecimento')
    op.drop_table('endereco')
    op.drop_table('socio_empresa')
    op.drop_table('municipio')
    op.drop_table('empresa_cnae')
    op.drop_table('uf')
    op.drop_table('socio')
    op.drop_table('empresa')
    op.drop_table('qualificacao')
    op.drop_table('pais')
    op.drop_table('natureza_juridica')
    op.drop_table('cnae')
    # ### end Alembic commands ###
