"""estabelecimento unique constraint multiple columns

Revision ID: 33b595fc0604
Revises: 3864ddeede13
Create Date: 2024-05-17 17:22:12.314081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b595fc0604'
down_revision = '3864ddeede13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cnpj_basico', 'cnpj_ordem', 'cnpj_dv'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
