"""socios indentifier and entry date

Revision ID: 36facbdb4d31
Revises: b8ce05837cf7
Create Date: 2024-05-16 15:44:58.229009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36facbdb4d31'
down_revision = 'b8ce05837cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identificador_socio', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('data_entrada_sociedade', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.drop_column('data_entrada_sociedade')
        batch_op.drop_column('identificador_socio')

    # ### end Alembic commands ###
