"""estabelecimento latitude and longitude

Revision ID: 3e443a87c08e
Revises: 01d81371195e
Create Date: 2024-04-18 16:43:44.874766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e443a87c08e'
down_revision = '01d81371195e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
