"""nome_fantasia from estabelecimento can be null

Revision ID: 61733a3fc619
Revises: 9ecdcb7aa3d0
Create Date: 2024-04-03 15:21:54.285158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61733a3fc619'
down_revision = '9ecdcb7aa3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
