"""alter representante_legal character limit

Revision ID: 6ab8102b7811
Revises: 7a0bfeb125fa
Create Date: 2024-04-01 22:06:47.666604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab8102b7811'
down_revision = '7a0bfeb125fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.alter_column('representante_legal',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=12),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.alter_column('representante_legal',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###
