"""add cnae_principal to empresa

Revision ID: 746a3f4a814d
Revises: 6ab8102b7811
Create Date: 2024-04-02 19:48:16.574549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746a3f4a814d'
down_revision = '6ab8102b7811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnae_principal_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'cnae', ['cnae_principal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cnae_principal_id')

    # ### end Alembic commands ###
