"""add cpnj_dv to estabelecimento

Revision ID: 818713edd8db
Revises: 8616a08795bd
Create Date: 2024-04-30 16:52:09.972479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818713edd8db'
down_revision = '8616a08795bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj_dv', sa.String(length=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.drop_column('cnpj_dv')

    # ### end Alembic commands ###
