"""latitude e longitude to endereco

Revision ID: 8616a08795bd
Revises: 3e443a87c08e
Create Date: 2024-04-24 17:19:30.483982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8616a08795bd'
down_revision = '3e443a87c08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Numeric(), nullable=True))

    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True))

    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
