"""endereco default values to empty string

Revision ID: 8fb03af25611
Revises: 33b595fc0604
Create Date: 2024-05-20 14:00:00.272598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb03af25611'
down_revision = '33b595fc0604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.alter_column('tipo_logradouro',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('complemento',
               existing_type=sa.VARCHAR(length=160),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.alter_column('complemento',
               existing_type=sa.VARCHAR(length=160),
               nullable=True)
        batch_op.alter_column('tipo_logradouro',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
