"""change empresa_cnae to empresa_cnae_secundarios

Revision ID: 9ecdcb7aa3d0
Revises: e8d66b530927
Create Date: 2024-04-02 19:58:04.452697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecdcb7aa3d0'
down_revision = 'e8d66b530927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa_cnae_secundarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnae_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cnae_id'], ['cnae.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('empresa_cnae')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa_cnae',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cnae_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cnae_id'], ['cnae.id'], name='empresa_cnae_cnae_id_fkey'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name='empresa_cnae_empresa_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='empresa_cnae_pkey')
    )
    op.drop_table('empresa_cnae_secundarios')
    # ### end Alembic commands ###
