"""fix ddd string max length

Revision ID: b12b2630eff4
Revises: ed6c30190108
Create Date: 2024-05-17 13:48:07.600432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12b2630eff4'
down_revision = 'ed6c30190108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.alter_column('ddd',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.alter_column('ddd',
               existing_type=sa.String(length=4),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###
