"""estabelecimento zero bullet

Revision ID: b8ce05837cf7
Revises: 124b186a1bf2
Create Date: 2024-05-16 15:39:48.397056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ce05837cf7'
down_revision = '124b186a1bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_situacao_cadastral', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('motivo_situacao_cadastral', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ddd', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('telefone')
        batch_op.drop_column('ddd')
        batch_op.drop_column('motivo_situacao_cadastral')
        batch_op.drop_column('data_situacao_cadastral')

    # ### end Alembic commands ###
