"""endereco complemento

Revision ID: e65ae9ec824f
Revises: b12b2630eff4
Create Date: 2024-05-17 16:39:14.752148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65ae9ec824f'
down_revision = 'b12b2630eff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complemento', sa.String(length=160), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.drop_column('complemento')

    # ### end Alembic commands ###
