"""motivo situacao cadastral

Revision ID: ed6c30190108
Revises: 36facbdb4d31
Create Date: 2024-05-16 16:52:51.375062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6c30190108'
down_revision = '36facbdb4d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motivo_situacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_situacao_cadastral_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'motivo_situacao', ['motivo_situacao_cadastral_id'], ['id'])
        batch_op.drop_column('motivo_situacao_cadastral')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_situacao_cadastral', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('motivo_situacao_cadastral_id')

    op.drop_table('motivo_situacao')
    # ### end Alembic commands ###
