"""qtd_estabelecimentos in uf

Revision ID: f03176d0be1d
Revises: 818713edd8db
Create Date: 2024-05-07 16:56:20.018065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03176d0be1d'
down_revision = '818713edd8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtd_estabelecimentos', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.drop_column('qtd_estabelecimentos')

    # ### end Alembic commands ###
