"""add situacao_cadastral to estabelecimento

Revision ID: f33bc0632770
Revises: 089c0b29c708
Create Date: 2024-03-26 14:21:15.794762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33bc0632770'
down_revision = '089c0b29c708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('situacao_cadastral', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.drop_column('situacao_cadastral')

    # ### end Alembic commands ###
